[package]
name = "backend-conversations"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
aws-sdk-s3 = "1.91.0"
dotenv = "0.15.0"
sqlx = "0.8.6"
tokio = { version = "1.45.1", features = ["full"]}

